# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Set environment variables (adjust as needed)
ENV MONGODB_URI=mongodb://mongo:27017/test
ENV NODE_ENV=production

# Start the application
CMD ["node", "index.js"]
